import type { Metadata } from "next";
import "./globals.css";
import OnchainProviders from "client/providers/coinbase";

export const metadata: Metadata = {
  title: "Agent Ethereum Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <OnchainProviders>
        <body className="flex flex-col font-mono">{children}</body>
      </OnchainProviders>
    </html>
  );
}
