import type { Metadata } from "next";
import "./globals.css";
import OnchainProviders from "client/providers/coinbase";
import { SidebarProvider, SidebarTrigger } from "../components/ui/sidebar";
import { AppSidebar } from "../components/app-sidebar";

export const metadata: Metadata = {
  title: "Agent Ethereum Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <OnchainProviders>
        <SidebarProvider>
          <AppSidebar />
          <body>
            <main className="flex flex-col w-full">
              <SidebarTrigger />
              {children}
            </main>
          </body>
        </SidebarProvider>
      </OnchainProviders>
    </html>
  );
}
